# Source:
# - https://github.com/joaopalmeiro/react-viz-logos/blob/v0.1.1/.github/workflows/npm-publish.yml
# - https://github.com/joaopalmeiro/svelte-logos/blob/v0.1.0/.github/workflows/npm-publish.yml
# - https://github.com/actions/setup-node
# - https://github.com/joaopalmeiro/code-profiler/blob/main/.github/workflows/publish.yml

name: Node.js Package

on:
  push:
    tags:
      - "v*"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org/"
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
